services:
  - type: web
    name: miramax-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
  - type: web
    name: miramax-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
